- name: Run frontend
  docker_container:
    name: frontend
    image: asgal/tp-devops-frontend
    recreate: true
    pull: always
    ports:
      - "8080:80"
    networks:
      - name: "my-network"