name: Ansible Deployment

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Force pull Docker images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i inventories/setup.yml playbook.yml