name: CI Pipeline
on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with: 
          java-version: 21
          distribution: 'temurin'

      - name: Build and test with Maven
        run: cd simple-api && mvn clean verify --file ./pom.xml 

      - name: SonarQube Analysis
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJETKEY }} -Dsonar.organization=dbsenzo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./simple-api/pom.xml 