name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
     #checkout your github code using actions/checkout@v4
      - uses: actions/checkout@v4

     #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with: 
          java-version: 21
          distribution: 'temurin'

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: cd simple-api && mvn clean verify --file ./pom.xml 

    # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located

          context: simple-api
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: database
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest

      - name: Build image and push httpd
        # DO the same for httpd
        uses: docker/build-push-action@v6
        with:
          context: http-server
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
